### ISSUE TITLE
Add pagination to the songs page

### ISSUE THREAD

**Issue by Primigenus** [Primigenus/salilda#2]

**Comment by dierat** [comment]
Pagination works except for one bug: the total number of songs returned by SongCount.findOne().count is 1142, but the total number of songs that are actually showing up is 1092. The discrepancy is equal to 50, which is the same number of songs being shown per page. This is probably not a coincidence.

**Comment by dierat** [comment]
Since pagination works, I'm closing this and opening a new bug regarding the song count discrepancy.
