### ISSUE TITLE
When clicking a person on a song page, navigate to the correct person

### ISSUE THREAD

**Issue by Primigenus** [Primigenus/salilda#4]
Right now when you click on a person on a song page you often end up on the right URL but with the wrong data being displayed. Something is broken with publications that we should look at.

**Comment by dierat** [comment]
Can't seem to replicate this bug.

**Comment by dierat** [comment]
Okay, I've seen this bug in action now, but I'm still confused about the pattern. It seems that opening the person link in a new tab prevents the bug from happening, and refreshing the page will cause the correct person to load. Also, the songs list is loading correctly; it's only the name (which in the person template is wrapped in a {{#with}} tag) that is wrong.

**Comment by dierat** [comment]
The pattern that I'm seeing right now is when you navigate to localhost and pick a song, a name of one of the people associated with that song (usually the singer) will become bound to the data context (whether or not you click on that person's link), and then that name will continue to show no matter what person page you navigate to.

**Comment by Primigenus** [comment]
Fixed in 6c6c1c8.
